In [ ]:
# Class No 1

In [41]:
import numpy as np

data = [1,2,3,4,5,6]
data1 = np.array(data)
print(data1)

print(f"normal list: {data *2}")
print(f"np array: {data1 * 2}")

data3 = np.zeros(6)
print(data3)

data4 = np.ones(6)
print(data4)

data5 = np.empty(6)
print(data5)

data6 = np.arange(1,6)
print(data6)

print(np.ones((3,3)))
txt = ["abc","def","ghi","jkl"]
print(np.array(data).reshape)

[1 2 3 4 5 6]
normal list: [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
np array: [ 2  4  6  8 10 12]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[1 2 3 4 5]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<built-in method reshape of numpy.ndarray object at 0x000002386F159B70>
